version: '3.8'

  tailscale-weaviate:
    image: tailscale/tailscale:latest
    hostname: tailscale-weaviate
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ./tailscale-weaviate/state:/var/lib/tailscale
      - ./TS_SERVE_CONFIG.json:/TS_SERVE_CONFIG.json
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/TS_SERVE_CONFIG.json
      - TS_EXTRA_ARGS=--advertise-routes=192.168.0.0/24 --advertise-tags=tag:infra --accept-routes --advertise-exit-node --ssh
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
 